/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_config_token1 = 1,
  anon_sym_LBRACK = 2,
  anon_sym_DQUOTE = 3,
  anon_sym_RBRACK = 4,
  sym_section_name = 5,
  aux_sym_subsection_name_token1 = 6,
  anon_sym_EQ = 7,
  sym_name = 8,
  anon_sym_yes = 9,
  anon_sym_on = 10,
  anon_sym_no = 11,
  anon_sym_off = 12,
  sym_true = 13,
  sym_false = 14,
  sym_integer = 15,
  aux_sym__quoted_string_content_token1 = 16,
  aux_sym__unquoted_string_token1 = 17,
  anon_sym_BANG = 18,
  sym_escape_sequence = 19,
  anon_sym_BSLASH = 20,
  aux_sym_comment_token1 = 21,
  sym_hotkey = 22,
  sym__comment_text = 23,
  sym_config = 24,
  sym_section = 25,
  sym_section_header = 26,
  sym__section_body = 27,
  sym_subsection_name = 28,
  sym_variable = 29,
  sym__value = 30,
  sym__boolean = 31,
  sym_string = 32,
  sym__shell_command_string = 33,
  sym__string_fragment = 34,
  sym__quoted_string = 35,
  aux_sym__quoted_string_content = 36,
  sym__unquoted_string = 37,
  sym_shell_command = 38,
  sym__line_continuation = 39,
  sym_comment = 40,
  aux_sym_config_repeat1 = 41,
  aux_sym__section_body_repeat1 = 42,
  aux_sym_subsection_name_repeat1 = 43,
  aux_sym_string_repeat1 = 44,
  aux_sym_comment_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_config_token1] = "config_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_RBRACK] = "]",
  [sym_section_name] = "section_name",
  [aux_sym_subsection_name_token1] = "subsection_name_token1",
  [anon_sym_EQ] = "=",
  [sym_name] = "name",
  [anon_sym_yes] = "true",
  [anon_sym_on] = "true",
  [anon_sym_no] = "false",
  [anon_sym_off] = "false",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_integer] = "integer",
  [aux_sym__quoted_string_content_token1] = "_quoted_string_content_token1",
  [aux_sym__unquoted_string_token1] = "_unquoted_string_token1",
  [anon_sym_BANG] = "!",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_hotkey] = "hotkey",
  [sym__comment_text] = "_comment_text",
  [sym_config] = "config",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym__section_body] = "_section_body",
  [sym_subsection_name] = "subsection_name",
  [sym_variable] = "variable",
  [sym__value] = "_value",
  [sym__boolean] = "_boolean",
  [sym_string] = "string",
  [sym__shell_command_string] = "_shell_command_string",
  [sym__string_fragment] = "_string_fragment",
  [sym__quoted_string] = "_quoted_string",
  [aux_sym__quoted_string_content] = "_quoted_string_content",
  [sym__unquoted_string] = "_unquoted_string",
  [sym_shell_command] = "shell_command",
  [sym__line_continuation] = "_line_continuation",
  [sym_comment] = "comment",
  [aux_sym_config_repeat1] = "config_repeat1",
  [aux_sym__section_body_repeat1] = "_section_body_repeat1",
  [aux_sym_subsection_name_repeat1] = "subsection_name_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_config_token1] = aux_sym_config_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_section_name] = sym_section_name,
  [aux_sym_subsection_name_token1] = aux_sym_subsection_name_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_name] = sym_name,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_on] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_off] = anon_sym_no,
  [sym_true] = anon_sym_yes,
  [sym_false] = anon_sym_no,
  [sym_integer] = sym_integer,
  [aux_sym__quoted_string_content_token1] = aux_sym__quoted_string_content_token1,
  [aux_sym__unquoted_string_token1] = aux_sym__unquoted_string_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_hotkey] = sym_hotkey,
  [sym__comment_text] = sym__comment_text,
  [sym_config] = sym_config,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym__section_body] = sym__section_body,
  [sym_subsection_name] = sym_subsection_name,
  [sym_variable] = sym_variable,
  [sym__value] = sym__value,
  [sym__boolean] = sym__boolean,
  [sym_string] = sym_string,
  [sym__shell_command_string] = sym__shell_command_string,
  [sym__string_fragment] = sym__string_fragment,
  [sym__quoted_string] = sym__quoted_string,
  [aux_sym__quoted_string_content] = aux_sym__quoted_string_content,
  [sym__unquoted_string] = sym__unquoted_string,
  [sym_shell_command] = sym_shell_command,
  [sym__line_continuation] = sym__line_continuation,
  [sym_comment] = sym_comment,
  [aux_sym_config_repeat1] = aux_sym_config_repeat1,
  [aux_sym__section_body_repeat1] = aux_sym__section_body_repeat1,
  [aux_sym_subsection_name_repeat1] = aux_sym_subsection_name_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_config_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_subsection_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_off] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__quoted_string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__unquoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_hotkey] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_text] = {
    .visible = false,
    .named = true,
  },
  [sym_config] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym__section_body] = {
    .visible = false,
    .named = true,
  },
  [sym_subsection_name] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym__boolean] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__shell_command_string] = {
    .visible = false,
    .named = true,
  },
  [sym__string_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__quoted_string_content] = {
    .visible = false,
    .named = false,
  },
  [sym__unquoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym_shell_command] = {
    .visible = true,
    .named = true,
  },
  [sym__line_continuation] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_config_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__section_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subsection_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_value = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 15,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 46,
};

static const TSCharacterRange sym_integer_character_set_1[] = {
  {'0', '9'}, {'E', 'E'}, {'G', 'G'}, {'K', 'K'}, {'M', 'M'}, {'P', 'P'}, {'T', 'T'}, {'Y', 'Z'},
  {'e', 'e'}, {'g', 'g'}, {'k', 'k'}, {'m', 'm'}, {'p', 'p'}, {'t', 't'}, {'y', 'z'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\n', 25,
        '\r', 1,
        '!', 78,
        '"', 27,
        '=', 46,
        '[', 26,
        '\\', 80,
        ']', 28,
        'f', 29,
        'n', 36,
        'o', 33,
        't', 37,
        'y', 30,
        '#', 81,
        ';', 81,
        '.', 43,
        '_', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '!') ADVANCE(78);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(88);
      if (lookahead == ']') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 78,
        '"', 27,
        '\\', 80,
        'f', 65,
        'n', 72,
        'o', 69,
        't', 73,
        'y', 66,
      );
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '#' < lookahead) &&
          lookahead != ';') ADVANCE(77);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(78);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        'U', 20,
        'u', 16,
        '"', 79,
        '\\', 79,
        'b', 79,
        'f', 79,
        'n', 79,
        'r', 79,
        't', 79,
      );
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(89);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 22:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_config_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'a') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(34);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'l') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'r') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 's') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 's') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'u') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_section_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (set_contains(sym_integer_character_set_1, 15, lookahead)) ADVANCE(43);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'X') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'x')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_subsection_name_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_subsection_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_yes);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_yes);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_on);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_on);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_no);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_no);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_off);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_off);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_true);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_true);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_false);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_false);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (set_contains(sym_integer_character_set_1, 15, lookahead)) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '!') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '"' < lookahead)) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym__quoted_string_content_token1);
      if (lookahead == '\\') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'a') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'f') ADVANCE(70);
      if (lookahead == 'n') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'f') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'l') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'o') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'r') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 's') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead == 'u') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__unquoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '\\') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      ADVANCE_MAP(
        'U', 20,
        'u', 16,
        '"', 79,
        '\\', 79,
        'b', 79,
        'f', 79,
        'n', 79,
        'r', 79,
        't', 79,
      );
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_hotkey);
      if (lookahead == '[') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_hotkey);
      if (lookahead == '[') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_hotkey);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__comment_text);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(88);
      if (lookahead == ']') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead == '[') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead == ']') ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__comment_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__comment_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(90);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 23},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 23},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_config_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_section_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_off] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_config] = STATE(49),
    [sym_section] = STATE(12),
    [sym_section_header] = STATE(39),
    [sym_comment] = STATE(47),
    [aux_sym_config_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_config_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      aux_sym__unquoted_string_token1,
    ACTIONS(17), 1,
      anon_sym_BANG,
    ACTIONS(19), 1,
      sym_escape_sequence,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    STATE(24), 1,
      sym_shell_command,
    STATE(41), 1,
      sym__shell_command_string,
    STATE(40), 3,
      sym__value,
      sym__boolean,
      sym_string,
    STATE(3), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
    ACTIONS(13), 7,
      anon_sym_yes,
      anon_sym_on,
      anon_sym_no,
      anon_sym_off,
      sym_true,
      sym_false,
      sym_integer,
  [43] = 5,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(27), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(4), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [66] = 5,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(29), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(34), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(4), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [89] = 5,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(40), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(42), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(6), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [112] = 5,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(27), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(4), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [135] = 5,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(48), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(8), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [158] = 5,
    ACTIONS(21), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(50), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
    ACTIONS(27), 3,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
    STATE(4), 5,
      sym__string_fragment,
      sym__quoted_string,
      sym__unquoted_string,
      sym__line_continuation,
      aux_sym_string_repeat1,
  [181] = 7,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      aux_sym_config_token1,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      aux_sym_comment_token1,
    STATE(39), 1,
      sym_section_header,
    STATE(47), 1,
      sym_comment,
    STATE(9), 2,
      sym_section,
      aux_sym_config_repeat1,
  [204] = 6,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(67), 1,
      anon_sym_BANG,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    STATE(25), 1,
      sym_shell_command,
    ACTIONS(65), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(20), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [225] = 7,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(73), 1,
      aux_sym_config_token1,
    ACTIONS(75), 1,
      sym_name,
    STATE(14), 1,
      aux_sym__section_body_repeat1,
    STATE(38), 1,
      sym_variable,
    STATE(43), 1,
      sym_comment,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [248] = 7,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      aux_sym_config_token1,
    STATE(39), 1,
      sym_section_header,
    STATE(47), 1,
      sym_comment,
    STATE(9), 2,
      sym_section,
      aux_sym_config_repeat1,
  [271] = 7,
    ACTIONS(83), 1,
      aux_sym_config_token1,
    ACTIONS(86), 1,
      sym_name,
    ACTIONS(89), 1,
      aux_sym_comment_token1,
    STATE(13), 1,
      aux_sym__section_body_repeat1,
    STATE(38), 1,
      sym_variable,
    STATE(43), 1,
      sym_comment,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [294] = 7,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(75), 1,
      sym_name,
    ACTIONS(94), 1,
      aux_sym_config_token1,
    STATE(13), 1,
      aux_sym__section_body_repeat1,
    STATE(38), 1,
      sym_variable,
    STATE(43), 1,
      sym_comment,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [317] = 2,
    ACTIONS(98), 1,
      anon_sym_BSLASH,
    ACTIONS(96), 6,
      aux_sym_config_token1,
      anon_sym_DQUOTE,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
      aux_sym_comment_token1,
  [329] = 3,
    ACTIONS(104), 1,
      anon_sym_BSLASH,
    ACTIONS(100), 3,
      aux_sym_config_token1,
      sym_escape_sequence,
      aux_sym_comment_token1,
    ACTIONS(102), 3,
      anon_sym_DQUOTE,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
  [343] = 2,
    ACTIONS(108), 1,
      anon_sym_BSLASH,
    ACTIONS(106), 6,
      aux_sym_config_token1,
      anon_sym_DQUOTE,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
      aux_sym_comment_token1,
  [355] = 2,
    ACTIONS(112), 1,
      anon_sym_BSLASH,
    ACTIONS(110), 6,
      aux_sym_config_token1,
      anon_sym_DQUOTE,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
      sym_escape_sequence,
      aux_sym_comment_token1,
  [367] = 4,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(22), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [382] = 4,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(22), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [397] = 4,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(65), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(20), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [412] = 4,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      anon_sym_BSLASH,
    ACTIONS(122), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(22), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [427] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      aux_sym_config_token1,
      anon_sym_LBRACK,
      sym_name,
      aux_sym_comment_token1,
  [435] = 3,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(128), 2,
      aux_sym__unquoted_string_token1,
      anon_sym_BANG,
    STATE(5), 2,
      sym__quoted_string,
      sym__unquoted_string,
  [447] = 3,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(130), 2,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
    STATE(19), 2,
      aux_sym__quoted_string_content,
      sym__line_continuation,
  [459] = 1,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      aux_sym_config_token1,
      anon_sym_LBRACK,
      sym_name,
      aux_sym_comment_token1,
  [467] = 3,
    ACTIONS(134), 1,
      aux_sym_config_token1,
    STATE(27), 1,
      aux_sym_comment_repeat1,
    ACTIONS(136), 2,
      sym_hotkey,
      sym__comment_text,
  [478] = 4,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(141), 1,
      aux_sym_subsection_name_token1,
    ACTIONS(143), 1,
      sym_escape_sequence,
    STATE(34), 1,
      aux_sym_subsection_name_repeat1,
  [491] = 3,
    ACTIONS(145), 1,
      aux_sym_config_token1,
    STATE(27), 1,
      aux_sym_comment_repeat1,
    ACTIONS(147), 2,
      sym_hotkey,
      sym__comment_text,
  [502] = 1,
    ACTIONS(52), 4,
      ts_builtin_sym_end,
      aux_sym_config_token1,
      anon_sym_LBRACK,
      aux_sym_comment_token1,
  [509] = 3,
    ACTIONS(149), 1,
      aux_sym_config_token1,
    STATE(29), 1,
      aux_sym_comment_repeat1,
    ACTIONS(151), 2,
      sym_hotkey,
      sym__comment_text,
  [520] = 4,
    ACTIONS(153), 1,
      aux_sym_subsection_name_token1,
    ACTIONS(155), 1,
      sym_escape_sequence,
    STATE(28), 1,
      aux_sym_subsection_name_repeat1,
    STATE(45), 1,
      sym_subsection_name,
  [533] = 1,
    ACTIONS(157), 4,
      ts_builtin_sym_end,
      aux_sym_config_token1,
      anon_sym_LBRACK,
      aux_sym_comment_token1,
  [540] = 4,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 1,
      aux_sym_subsection_name_token1,
    ACTIONS(164), 1,
      sym_escape_sequence,
    STATE(34), 1,
      aux_sym_subsection_name_repeat1,
  [553] = 1,
    ACTIONS(98), 4,
      anon_sym_DQUOTE,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
      anon_sym_BSLASH,
  [560] = 2,
    ACTIONS(169), 1,
      anon_sym_EQ,
    ACTIONS(167), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
  [568] = 1,
    ACTIONS(171), 3,
      aux_sym__quoted_string_content_token1,
      sym_escape_sequence,
      anon_sym_BSLASH,
  [574] = 3,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(173), 1,
      aux_sym_config_token1,
    STATE(50), 1,
      sym_comment,
  [584] = 2,
    ACTIONS(175), 1,
      aux_sym_config_token1,
    STATE(33), 1,
      sym__section_body,
  [591] = 1,
    ACTIONS(177), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
  [596] = 1,
    ACTIONS(23), 2,
      aux_sym_config_token1,
      aux_sym_comment_token1,
  [601] = 2,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_RBRACK,
  [608] = 1,
    ACTIONS(173), 1,
      aux_sym_config_token1,
  [612] = 1,
    ACTIONS(183), 1,
      aux_sym_config_token1,
  [616] = 1,
    ACTIONS(185), 1,
      anon_sym_DQUOTE,
  [620] = 1,
    ACTIONS(187), 1,
      aux_sym_config_token1,
  [624] = 1,
    ACTIONS(189), 1,
      aux_sym_config_token1,
  [628] = 1,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
  [632] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [636] = 1,
    ACTIONS(195), 1,
      aux_sym_config_token1,
  [640] = 1,
    ACTIONS(197), 1,
      aux_sym_config_token1,
  [644] = 1,
    ACTIONS(199), 1,
      sym_section_name,
  [648] = 1,
    ACTIONS(201), 1,
      aux_sym_config_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 89,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 158,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 204,
  [SMALL_STATE(11)] = 225,
  [SMALL_STATE(12)] = 248,
  [SMALL_STATE(13)] = 271,
  [SMALL_STATE(14)] = 294,
  [SMALL_STATE(15)] = 317,
  [SMALL_STATE(16)] = 329,
  [SMALL_STATE(17)] = 343,
  [SMALL_STATE(18)] = 355,
  [SMALL_STATE(19)] = 367,
  [SMALL_STATE(20)] = 382,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 412,
  [SMALL_STATE(23)] = 427,
  [SMALL_STATE(24)] = 435,
  [SMALL_STATE(25)] = 447,
  [SMALL_STATE(26)] = 459,
  [SMALL_STATE(27)] = 467,
  [SMALL_STATE(28)] = 478,
  [SMALL_STATE(29)] = 491,
  [SMALL_STATE(30)] = 502,
  [SMALL_STATE(31)] = 509,
  [SMALL_STATE(32)] = 520,
  [SMALL_STATE(33)] = 533,
  [SMALL_STATE(34)] = 540,
  [SMALL_STATE(35)] = 553,
  [SMALL_STATE(36)] = 560,
  [SMALL_STATE(37)] = 568,
  [SMALL_STATE(38)] = 574,
  [SMALL_STATE(39)] = 584,
  [SMALL_STATE(40)] = 591,
  [SMALL_STATE(41)] = 596,
  [SMALL_STATE(42)] = 601,
  [SMALL_STATE(43)] = 608,
  [SMALL_STATE(44)] = 612,
  [SMALL_STATE(45)] = 616,
  [SMALL_STATE(46)] = 620,
  [SMALL_STATE(47)] = 624,
  [SMALL_STATE(48)] = 628,
  [SMALL_STATE(49)] = 632,
  [SMALL_STATE(50)] = 636,
  [SMALL_STATE(51)] = 640,
  [SMALL_STATE(52)] = 644,
  [SMALL_STATE(53)] = 648,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shell_command_string, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shell_command_string, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shell_command_string, 4, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shell_command_string, 5, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_body, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__section_body_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__section_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__section_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__section_body_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section_body, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_continuation, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_continuation, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unquoted_string, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shell_command, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unquoted_string, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_string, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_string, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_string, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0), SHIFT_REPEAT(22),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__quoted_string_content, 2, 0, 0), SHIFT_REPEAT(53),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__section_body_repeat1, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subsection_name, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subsection_name_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subsection_name_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subsection_name_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shell_command, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 6, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_git_config(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "git_config",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
